"use client";
import {useState} from 'react';
import Link from 'next/link';
import {CarFront,Plane,HeartHandshake,Sparkles,MapPin,Music,Briefcase,ArrowUpRight} from 'lucide-react';
import {EditorialImage,type Scene} from './EditorialImage';
import {T} from './Locale';
const rides=[
 {id:'standard',en:'Everyday',ar:'كل يوم',title:'A simpler everyday journey.',titleAr:'مشوار يومي أسهل.',description:'Explore Standard for everyday plans. Check the app for vehicles and fares at your pickup.',descriptionAr:'اكتشف ستاندرد لخططك اليومية. تحقّق من السيارات والأسعار في موقعك عبر التطبيق.',scene:'city',Icon:CarFront},
 {id:'premium',en:'Comfort',ar:'الراحة',title:'A little room to unwind.',titleAr:'مساحة أكثر للاسترخاء.',description:'Explore Premium for a more comfortable journey where available. Vehicle details are shown before booking.',descriptionAr:'اكتشف بريميوم لرحلة أكثر راحة حيث يتوفّر. تظهر تفاصيل السيارة قبل الحجز.',scene:'cabin',Icon:Sparkles},
 {id:'airport',en:'Airport',ar:'المطار',title:'Make the journey part of the trip.',titleAr:'اجعل المشوار جزءاً من السفر.',description:'Review your terminal, luggage and pickup needs before your airport journey.',descriptionAr:'راجع المبنى والأمتعة واحتياجات الانطلاق قبل رحلة المطار.',scene:'people',Icon:Plane},
 {id:'friend',en:'Assistance',ar:'المساعدة',title:'Find the support your journey needs.',titleAr:'اكتشف المساعدة المناسبة لرحلتك.',description:'Explore supported assistance journeys in the app. This service is not emergency medical transport.',descriptionAr:'اكتشف رحلات المساعدة المدعومة في التطبيق. هذه الخدمة ليست للنقل الطبي الطارئ.',scene:'people',Icon:HeartHandshake}
];
const cabin=[
 {id:'journey',en:'Journey',ar:'الرحلة',title:'Stay close to your journey.',titleAr:'تابع تفاصيل رحلتك.',description:'Supported cabin displays show trip progress, destination and arrival information for your active journey.',descriptionAr:'تعرض الشاشات المدعومة مسار رحلتك والوجهة ومعلومات الوصول.',scene:'cabin',Icon:MapPin},
 {id:'entertainment',en:'Entertainment',ar:'الترفيه',title:'Settle in. Switch off.',titleAr:'استرخِ واستمتع.',description:'Explore entertainment and family features when they are enabled on your vehicle’s cabin screen.',descriptionAr:'اكتشف الترفيه ومزايا العائلة عندما تكون مفعّلة على شاشة السيارة.',scene:'cabin',Icon:Music},
 {id:'work',en:'Work',ar:'العمل',title:'A calmer space between meetings.',titleAr:'مساحة هادئة بين الاجتماعات.',description:'Work Mode and Wi-Fi depend on the equipped vehicle and available connection. Check onboard availability.',descriptionAr:'يعتمد وضع العمل وWi-Fi على تجهيز السيارة والاتصال المتاح. تحقّق من التوفّر داخل السيارة.',scene:'cabin',Icon:Briefcase}
];
export function ExperienceExplorer({connect=false}:{connect?:boolean}){const choices=connect?cabin:rides;const [selected,setSelected]=useState(0);const item=choices[selected];return <section className="experience-explorer" aria-label={connect?'Explore Connect':'Explore ride choices'}><div className="section-heading"><div><p className="eyebrow"><T en={connect?'MAKE YOURSELF AT HOME':'FIND YOUR KIND OF RIDE'} ar={connect?'اشعر بالراحة':'اكتشف مشوارك'}/></p><h2><T en={connect?'Your cabin. Your moment.':'What does your day need?'} ar={connect?'مقصورتك. لحظتك.':'ماذا يحتاج يومك؟'}/></h2></div></div><div className="explorer-options" role="group" aria-label={connect?'Cabin modes':'Journey preferences'}>{choices.map((choice,index)=><button type="button" key={choice.id} aria-pressed={index===selected} onClick={()=>setSelected(index)}><choice.Icon size={19}/><T en={choice.en} ar={choice.ar}/></button>)}</div><div className="explorer-result"><EditorialImage scene={item.scene as Scene}/><div aria-live="polite" aria-atomic="true"><item.Icon className="section-icon" size={32}/><h3><T en={item.title} ar={item.titleAr}/></h3><p><T en={item.description} ar={item.descriptionAr}/></p><Link className="button" href={connect?'/download#app-options':item.id==='airport'?'/airport':`/ride-types#${item.id}`}><T en={connect?'Explore the app':'Explore this journey'} ar={connect?'اكتشف التطبيق':'اكتشف هذا المشوار'}/><ArrowUpRight size={18}/></Link></div></div></section>}
