import Link from 'next/link';
import {CircleHelp,ChevronDown,ArrowUpRight} from 'lucide-react';
import {T} from './Locale';
const items=[
 ['Where do I book a ride?','أين أحجز مشواراً؟','Open your Passenger app, choose a destination, review the available ride and fare, and confirm your pickup. Website booking is not available.','افتح تطبيق الراكب واختر الوجهة وراجع الرحلة والسعر وأكّد الانطلاق. الحجز عبر الموقع غير متاح.','/download','Explore the app','اكتشف التطبيق'],
 ['Where are the app download links?','أين روابط تنزيل التطبيق؟','Official store links are pending publication. The store buttons explain their current availability. We do not link to unofficial downloads.','روابط المتاجر الرسمية بانتظار النشر. توضّح أزرار المتاجر حالة التوفّر الحالية. لا نوفّر روابط تنزيل غير رسمية.','/download#app-options','View download options','عرض خيارات التنزيل'],
 ['How do I apply as a driver?','كيف أقدّم طلباً كسائق؟','Visit the driver page to review the application fields and required documents. Submission availability is shown above the form.','زر صفحة السائقين لمراجعة الحقول والوثائق المطلوبة. تظهر حالة توفّر الإرسال أعلى النموذج.','/drivers#driver-application','View the application','عرض الطلب'],
 ['How do I get help with a trip or payment?','كيف أحصل على مساعدة لرحلة أو دفعة؟','In your installed Passenger app, open the relevant trip or transaction, then contact Support. Keep verification codes and card details private.','في تطبيق الراكب، افتح الرحلة أو المعاملة المعنية ثم تواصل مع الدعم. احتفظ برموز التحقّق وبيانات البطاقة سريّة.','/account','Account information','معلومات الحساب'],
 ['Can my company or business join?','هل يمكن لشركتي أو نشاطي الانضمام؟','Company travel and merchant partnerships have separate application journeys. Each is reviewed before activation.','لتنقّل الشركات والشراكات التجارية مساران منفصلان للتقديم. يُراجع كل طلب قبل التفعيل.','/corporate','Explore company travel','اكتشف تنقّل الشركات']
];
export function HelpCenter(){return <section id="help-center" className="help-center"><CircleHelp className="section-icon" size={32}/><h2><T en="A helpful place to start." ar="نقطة بداية مفيدة."/></h2>{items.map(([en,ar,detail,detailAr,href,action,actionAr])=><details key={en}><summary><T en={en} ar={ar}/><ChevronDown size={19}/></summary><p><T en={detail} ar={detailAr}/></p><Link className="text-link" href={href}><T en={action} ar={actionAr}/><ArrowUpRight size={17}/></Link></details>)}</section>}
