import {DriverApplication} from './DriverApplication';
import {JourneyLinks} from './JourneyLinks';
import Link from 'next/link';
import {preservedTopics} from '@/lib/preserved-topics';
import { ArrowUpRight } from 'lucide-react';
import { T } from './Locale';
import { Application } from './Application';
import { Account } from './Account';
import { PublishedContent } from './PublishedContent';
type Copy = {
    title: [
        string,
        string
    ];
    intro: [
        string,
        string
    ];
    cards?: [
        string,
        string,
        string,
        string,
        string?
    ][];
};
export const pages: Record<string, Copy> = {
    'ride-types': { title: ['Your day. Your kind of ride.', 'يومك. مشوار على ذوقك.'], intro: ['Choose your journey in the Passenger app. Pickup coverage, vehicle choices, pricing and scheduling are confirmed there before you book.', 'اختر رحلتك في تطبيق الراكب. تأكّد من التغطية والسيارات والأسعار والمواعيد قبل الحجز.'], cards: [['Standard', 'ستاندرد', 'Everyday electric travel. See available vehicles and fares in the app.', 'تنقّل كهربائي يومي. شاهد السيارات والأسعار المتاحة في التطبيق.', 'standard'], ['Premium', 'بريميوم', 'Explore a more comfortable ride option where available.', 'اكتشف خياراً أكثر راحة حيث يتوفّر.', 'premium'], ['GrabFriend & assistance', 'GrabFriend والمساعدة', 'Check supported passenger and assistance journeys in the app. Do not use this service for emergency medical transport.', 'تحقّق من الرحلات وخدمات المساعدة المدعومة في التطبيق. هذه الخدمة ليست للنقل الطبي الطارئ.', 'friend'], ['Airport', 'المطار', 'Confirm your airport pickup details and luggage needs in the app.', 'أكّد تفاصيل الانطلاق واحتياجات الأمتعة في التطبيق.', 'airport'], ['Scheduling', 'الحجز المسبق', 'Use scheduling only when offered for your pickup, destination and time in the app.', 'استخدم الحجز المسبق عندما يظهر لموقعك ووجهتك وموعدك في التطبيق.', 'scheduling'], ['Grocery journeys', 'مشاوير البقالة', 'Check the app for supported grocery journeys. No retailer partnership is implied.', 'تحقّق من التطبيق لمشاوير البقالة المدعومة. لا يُقصد بذلك تأكيد شراكة مع متجر معيّن.', 'grocery']] },
    membership: { title: ['Welcome to GrabClub.', 'أهلاً بك في GrabClub.'], intro: ['The same Passenger account connects your eligible plans and active membership. Sign in to see the catalog returned for your account.', 'حساب الراكب نفسه يربط خططك المؤهّلة وعضويتك النشطة. سجّل الدخول لعرض الخطط المتاحة لحسابك.'], cards: [['Paid subscriptions', 'الاشتراكات المدفوعة', 'Online purchase is not available until payment providers, plan prices and billing terms are approved.', 'الشراء الإلكتروني غير متاح قبل اعتماد مزوّدي الدفع والأسعار وشروط الفوترة.'], ['Earned qualification', 'التأهّل المكتسب', 'Qualification depends on approved program rules. It is separate from a paid subscription.', 'يعتمد التأهّل على قواعد البرنامج المعتمدة وهو منفصل عن الاشتراك المدفوع.'], ['Promotional credit', 'الرصيد الترويجي', 'Credit is subject to its own terms and expiry. It is not a recurring membership.', 'للرصيد شروطه وصلاحيته الخاصة، وهو ليس عضوية متجدّدة.'], ['Redeemable points', 'النقاط القابلة للاستبدال', 'Points and achievements will appear only when an authoritative Passenger rewards integration is available.', 'تظهر النقاط والإنجازات عند توفّر ربط معتمد لمكافآت الراكب.']] },
    corporate: { title: ['Your people. Going places.', 'فريقك، إلى وجهات جديدة.'], intro: ['Tell us about your team and its travel needs. Corporate travel is reviewed separately from merchant partnerships.', 'أخبرنا عن فريقك واحتياجات التنقّل. تخضع رحلات الشركات لمراجعة منفصلة عن الشراكات التجارية.'], cards: [['Apply', 'قدّم طلباً', 'Share your team size, locations and travel needs.', 'شارك حجم فريقك ومواقعه واحتياجات التنقّل.'], ['Review together', 'مراجعة مشتركة', 'GrabMe reviews eligibility and agrees a program with your organization.', 'تراجع GrabMe الأهلية وتتفق مع شركتك على البرنامج.'], ['Approved access', 'وصول معتمد', 'Employee access, policies, reports and billing depend on the approved program. No credit or monthly invoicing is promised.', 'يعتمد وصول الموظفين والسياسات والتقارير والفوترة على البرنامج المعتمد. لا يوجد وعد بائتمان أو فواتير شهرية.']] },
    partners: { title: ["Good businesses. Better together.", 'أعمال مميّزة. أفضل معاً.'], intro: ['Retail, restaurants, hotels, venues, rewards and advertising: explore a partnership with GrabMe. Applications are reviewed before any partnership is activated.', 'تجارة ومطاعم وفنادق ومكافآت وإعلانات: اكتشف الشراكة مع GrabMe. تُراجع الطلبات قبل تفعيل أي شراكة.'] },
    contact: { title: ['A little help along the way.', 'مساعدة في كل خطوة.'], intro: ['For help with your account, trip or membership, open Support in the Passenger app so the team can work with the right account and journey.', 'للمساعدة في حسابك أو رحلتك أو عضويتك، افتح الدعم في تطبيق الراكب ليرتبط طلبك بالحساب والرحلة الصحيحة.'], cards: [['Trip or payment question', 'استفسار عن رحلة أو دفعة', 'Open the relevant trip or transaction in the app and contact Support. Do not send card details or verification codes.', 'افتح الرحلة أو المعاملة في التطبيق وتواصل مع الدعم. لا ترسل بيانات البطاقة أو رموز التحقّق.'], ['Sign-in recovery', 'استعادة الدخول', 'Use your registered phone number and request a new verification code after the cooldown.', 'استخدم رقمك المسجّل واطلب رمز تحقّق جديداً بعد انتهاء فترة الانتظار.'], ['Immediate danger', 'خطر فوري', 'Contact the local emergency services. GrabMe Support is not an emergency service.', 'اتصل بخدمات الطوارئ المحلية. دعم GrabMe ليس خدمة طوارئ.']] },
    download: { title: ['Your next ride starts in the app.', 'مشوارك التالي يبدأ في التطبيق.'], intro: ['Use the GrabMe Passenger app to check your pickup, choose your ride and review the fare before booking.', 'استخدم تطبيق GrabMe للراكب لتحديد موقع الانطلاق واختيار الرحلة ومراجعة السعر قبل الحجز.'], cards: [['Already have GrabMe?', 'لديك GrabMe؟', 'Open your installed Passenger app and sign in with your phone number. Website ride booking is not available.', 'افتح تطبيق الراكب المثبّت وسجّل الدخول برقم هاتفك. حجز الرحلات عبر الموقع غير متاح.'], ['App store links', 'روابط متاجر التطبيقات', 'Verified public store links are pending. This preview does not provide an unofficial download or an unverified store link.', 'روابط المتاجر العامة الموثّقة قيد التأكيد. لا توفّر هذه المعاينة تنزيلاً غير رسمي أو رابطاً غير موثّق.']] },
    account: { title: ['One account. Every journey.', 'حساب واحد. لكل مشوار.'], intro: ['Sign in with your existing Passenger identity to see your membership and wallet activity.', 'سجّل الدخول بحساب الراكب الحالي لعرض عضويتك وحركة محفظتك.'] },
    students: { title: ['A smarter route to your day.', 'طريق أذكى ليومك.'], intro: ['Student eligibility is verified through your existing Passenger account. Benefits depend on your approved university program and active membership.', 'تُتحقّق أهلية الطالب من خلال حساب الراكب الحالي. تعتمد المزايا على برنامج الجامعة المعتمد والعضوية النشطة.'], cards: [['Check your eligibility', 'تحقّق من أهليتك', 'Sign in to view your student verification status. For verification changes, contact Support in the app.', 'سجّل الدخول لعرض حالة التحقّق الطلابي. لتحديثها، تواصل مع الدعم في التطبيق.']] },
    airport: { title: ['From your doorstep to departures.', 'من بابك إلى المغادرة.'], intro: ['Plan your airport journey in the Passenger app. Confirm pickup availability, terminal meeting details and luggage requirements before booking.', 'خطّط لرحلة المطار في تطبيق الراكب. تأكّد من التوفّر ونقطة اللقاء واحتياجات الأمتعة قبل الحجز.'], cards: [['Before you travel', 'قبل السفر', 'Review your pickup time and destination in the app. Allow for traffic, check-in and airport requirements.', 'راجع موعد الانطلاق والوجهة في التطبيق وخصّص وقتاً للازدحام وإجراءات المطار.']] },
    'grabme-connect': { title: ['Your ride, from the inside.', 'رحلتك، من الداخل.'], intro: ['GrabMe Connect brings a connected cabin experience to equipped vehicles. Features depend on the vehicle, active trip and supported services. Technology by MetaHaus.', 'يقدّم GrabMe Connect تجربة مقصورة متصلة في السيارات المجهّزة. تعتمد المزايا على السيارة والرحلة والخدمات المدعومة. التكنولوجيا من MetaHaus.'], cards: [['Stay with your journey', 'تابع رحلتك', 'Explore available trip information and cabin features in your equipped vehicle.', 'اكتشف معلومات الرحلة ومزايا المقصورة المتاحة في السيارة المجهّزة.']] },
    features: { title: ['Built around your journey.', 'مصمّم حول رحلتك.'], intro: ['Your Passenger app connects trip information, your account and supported ride choices. Check the app for the features enabled for your journey.', 'يربط تطبيق الراكب معلومات الرحلة وحسابك وخيارات التنقّل المدعومة. تحقّق من المزايا المتاحة لرحلتك في التطبيق.'] },
    about: { title: ['A little more ease. Every day.', 'راحة أكثر. كل يوم.'], intro: ['GrabMe brings electric mobility and connected passenger experiences together in Lebanon. GrabMe S.A.L is the fare-collecting entity. Technology by MetaHaus.', 'تجمع GrabMe التنقّل الكهربائي وتجارب الركاب المتصلة في لبنان. GrabMe S.A.L هي الجهة المحصّلة للأجرة. التكنولوجيا من MetaHaus.'] },
    drivers: { title: ['Drive with GrabMe.', 'قد مع GrabMe.'], intro: ['Join the electric journey. Explore the Driver experience and apply with your personal details, driving experience, vehicle preferences and documents.', 'انضم إلى رحلة التنقّل الكهربائي. اكتشف تجربة السائق وقدّم معلوماتك وخبرتك وتفضيلات السيارة والوثائق.'] },
    'mission-control': { title: ['Connected operations.', 'عمليات متصلة.'], intro: ['Authorized GrabMe staff manage operations in the existing Admin system. This public website does not provide staff access or expose operational records.', 'يدير موظفو GrabMe المخوّلون العمليات في نظام الإدارة الحالي. لا يوفّر هذا الموقع العام دخول الموظفين أو بيانات العمليات.'] },
    privacy: { title: ['Your privacy matters.', 'خصوصيتك مهمّة.'], intro: ['Preview notice: the approved website privacy policy is pending legal review. Do not submit personal data through preview application forms. Connected sign-in uses the existing Passenger API.', 'إشعار المعاينة: سياسة خصوصية الموقع المعتمدة بانتظار المراجعة القانونية. لا تقدّم بيانات شخصية في نماذج المعاينة. يستخدم تسجيل الدخول المتصل واجهة الراكب الحالية.'], cards: [['Account session', 'جلسة الحساب', 'The website keeps your access token in memory only. Signing out or reloading clears it. Your language preference is stored locally.', 'يحتفظ الموقع برمز الدخول في الذاكرة فقط ويُزال عند الخروج أو إعادة التحميل. يُحفظ اختيار اللغة محلياً.']] },
    terms: { title: ['Clear terms for your journey.', 'شروط واضحة لرحلتك.'], intro: ['The approved website terms are pending review. This preview does not sell subscriptions, take payments or accept ride bookings. Review the terms shown in your Passenger app for available services.', 'شروط الموقع المعتمدة بانتظار المراجعة. لا تبيع هذه المعاينة اشتراكات ولا تستقبل دفعات أو حجوزات. راجع شروط الخدمات المتاحة في تطبيق الراكب.'] },
    'account-deletion': { title: ['Manage your account data.', 'إدارة بيانات حسابك.'], intro: ['Contact Support in the Passenger app for help with account deletion. The website does not yet submit deletion requests. Applicable retention requirements must be explained in the approved privacy policy.', 'تواصل مع الدعم في تطبيق الراكب للمساعدة في حذف الحساب. لا يرسل الموقع طلبات الحذف بعد. يجب توضيح متطلبات الاحتفاظ بالبيانات في سياسة الخصوصية المعتمدة.'] },
};
export function InfoPage({ slug }: {
    slug: string;
}) { const data = pages[slug]; return <div className="wrap info-page"><section className="page-heading"><p className="eyebrow">GRABME / {slug.replaceAll('-', ' ')}</p><h1><T en={data.title[0]} ar={data.title[1]}/></h1><p className="intro"><T en={data.intro[0]} ar={data.intro[1]}/></p>{slug === "drivers" && <a className="button" href="#driver-application"><T en="Apply as a driver" ar="قدّم طلباً كسائق"/></a>}</section>{slug === "contact" && <JourneyLinks/>}{slug === "drivers" && <DriverApplication/>}{data.cards && <div className="two-grid info-cards">{data.cards.map(([en, ar, desc, descAr, id]) => <section className="feature-panel" id={id} key={en}><h2><T en={en} ar={ar}/></h2><p><T en={desc} ar={descAr}/></p></section>)}</div>}{slug === 'ride-types' && <PublishedContent />}{slug === 'download' && <PublishedContent download/>}{preservedTopics[slug] && <div id={slug === "grabme-connect" ? "experience" : undefined} className="two-grid info-cards">{preservedTopics[slug].map(([en,ar,desc,descAr])=><section className="feature-panel" key={en}><h2><T en={en} ar={ar}/></h2><p><T en={desc} ar={descAr}/></p></section>)}</div>}{slug === 'partners'  && <Application />}{slug === 'corporate' && <Application corporate/>}{slug === 'account' && <Account />}{!['account', 'privacy', 'terms', 'account-deletion', 'download', 'partners', 'corporate', 'drivers', 'mission-control'].includes(slug) && <div className="actions"><Link className="button" href={['membership', 'students'].includes(slug) ? '/account' : '/download'}><T en={['membership', 'students'].includes(slug) ? 'View my account' : 'Continue in the app'} ar={['membership', 'students'].includes(slug) ? 'عرض حسابي' : 'تابع في التطبيق'}/><ArrowUpRight size={18}/></Link></div>}</div>; }
