import Link from 'next/link';
import {ArrowUpRight,CarFront,Users,Plane,GraduationCap,Building2,HeartHandshake,ShieldCheck,Smartphone,Sparkles,MapPin,LifeBuoy,LayoutDashboard,Leaf} from 'lucide-react';
import {EditorialImage,type Scene} from './EditorialImage';
import {T} from './Locale';
const destinations:Record<string,[string,string,string,Scene]>={
 'ride-types':['/download#app-options','Explore the app','اكتشف التطبيق','page-ride-types'],membership:['/account','View my account','عرض حسابي','page-membership'],corporate:['/corporate#business-application','Tell us about your team','أخبرنا عن فريقك','page-corporate'],partners:['/partners#business-application','Explore a partnership','اكتشف الشراكة','page-partners'],contact:['/contact#help-center','Find an answer','اعثر على إجابة','page-contact'],download:['/download#app-options','View download options','عرض خيارات التنزيل','page-download'],account:['/contact#help-center','Sign-in help','المساعدة في الدخول','page-account'],students:['/account','Check my account','تحقّق من حسابي','page-students'],airport:['/download#app-options','Plan in the app','خطّط في التطبيق','page-airport'],'grabme-connect':['/grabme-connect#experience','Explore the cabin','اكتشف المقصورة','page-grabme-connect'],features:['/ride-types','Find your journey','اكتشف رحلتك','page-features'],about:['/features','Explore GrabMe','اكتشف GrabMe','page-about'],drivers:['/drivers#driver-application','Apply as a driver','قدّم طلباً كسائق','page-drivers'],'mission-control':['/contact#help-center','Find the right help','اكتشف المساعدة المناسبة','page-mission-control'],privacy:['/account-deletion','Manage account data','إدارة بيانات الحساب','page-privacy'],terms:['/contact#help-center','Get help','احصل على المساعدة','page-terms'],'account-deletion':['/contact#help-center','See support steps','عرض خطوات الدعم','page-account-deletion']};
const icons:Record<string,typeof CarFront>={'ride-types':CarFront,membership:Sparkles,corporate:Building2,partners:HeartHandshake,contact:LifeBuoy,download:Smartphone,account:Users,students:GraduationCap,airport:Plane,'grabme-connect':Smartphone,features:MapPin,about:Leaf,drivers:CarFront,'mission-control':LayoutDashboard,privacy:ShieldCheck,terms:ShieldCheck,'account-deletion':ShieldCheck};
export function PageImage({slug}:{slug:string}){const d=destinations[slug];if(!d)return null;return <EditorialImage scene={d[3]} href={d[0]} label={[d[1],d[2]]} priority/>}
export function PageIcon({slug}:{slug:string}){const Icon=icons[slug]??MapPin;return <Icon size={27} className="section-icon" aria-hidden="true"/>}
export function CardAction({slug}:{slug:string}){const d=destinations[slug]??destinations.contact;return <Link className="text-link card-action" href={d[0]}><T en={d[1]} ar={d[2]}/><ArrowUpRight size={17}/></Link>}
export function NextJourneys(){return <section className="next-journeys"><div><p className="eyebrow"><T en="KEEP EXPLORING" ar="تابع الاكتشاف"/></p><h2><T en="Where to next?" ar="إلى أين الآن؟"/></h2></div><div className="next-links">{[['/ride-types','Find a ride','اكتشف مشواراً',CarFront],['/drivers','Drive with GrabMe','قد مع GrabMe',CarFront],['/corporate','For your team','لفريقك',Building2],['/contact#help-center','Get some help','احصل على المساعدة',LifeBuoy]].map(([href,en,ar,Icon])=>{const I=Icon as typeof CarFront;return <Link key={href as string} href={href as string}><I size={22}/><T en={en as string} ar={ar as string}/><ArrowUpRight size={18}/></Link>})}</div></section>}
