"use client";
import Link from 'next/link';
import {Appearance} from './Appearance';
import { useState } from 'react';
import { ArrowUpRight, Menu, X } from 'lucide-react';
import { T, useLocale } from './Locale';
const links = [['Ride with GrabMe', 'اركب مع GrabMe', '/ride-types'], ['Drive with GrabMe', 'قد مع GrabMe', '/drivers'], ['GrabClub', 'نادي GrabClub', '/membership'], ['For Business', 'للشركات', '/corporate'], ['Partner with Us', 'كن شريكاً', '/partners'], ['Help', 'المساعدة', '/contact']];
export function Header() { const [open, setOpen] = useState(false); const { toggle, ar } = useLocale(); return <><a className="skip" href="#main"><T en="Skip to content" ar="انتقل إلى المحتوى"/></a><header className="header"><Link className="wordmark" href="/" aria-label="GrabMe home">grabme<span>●</span></Link><nav className={open ? 'nav open' : 'nav'} aria-label={ar ? 'التنقل الرئيسي' : 'Main navigation'}>{links.map(([en, ar, href]) => <Link onClick={() => setOpen(false)} key={href} href={href}><T en={en} ar={ar}/></Link>)}</nav><div className="header-actions"><Appearance/><button className="language" onClick={toggle} aria-label={ar ? 'Switch to English' : 'التبديل إلى العربية'}>{ar ? 'EN' : 'عربي'}</button><Link className="signin" href="/account"><T en="Sign in" ar="دخول"/></Link><Link className="button small" href="/download"><T en="Get the app" ar="احصل على التطبيق"/><ArrowUpRight size={16}/></Link><button className="menu-button" aria-expanded={open} aria-controls="mobile-nav" aria-label={ar ? 'القائمة' : 'Menu'} onClick={() => setOpen(!open)}>{open ? <X /> : <Menu />}</button></div></header><div id="mobile-nav" hidden={!open} className="mobile-nav">{links.map(([en, ar, href]) => <Link onClick={() => setOpen(false)} key={href} href={href}><T en={en} ar={ar}/></Link>)}</div></>; }
export function Footer() { return <footer className="footer"><div><Link className="wordmark" href="/">grabme<span>●</span></Link><p><T en="A little more ease. Everywhere you go." ar="راحة أكثر، أينما ذهبت."/></p><small><T en="Technology by MetaHaus" ar="التكنولوجيا من MetaHaus"/></small></div><div className="footer-links">{[['About', 'عن GrabMe', '/about'], ['Previous website', 'الموقع السابق', '/previous-site'], ['Students', 'للطلاب', '/students'], ['Platform', 'المنصّة', '/features'], ['Mission Control', 'إدارة العمليات', '/mission-control'], ['Drive with GrabMe', 'قد مع GrabMe', '/drivers'], ['Airport', 'المطار', '/airport'], ['GrabMe Connect', 'GrabMe Connect', '/grabme-connect'], ['Privacy', 'الخصوصية', '/privacy'], ['Terms', 'الشروط', '/terms'], ['Delete account', 'حذف الحساب', '/account-deletion'], ['Help', 'المساعدة', '/contact']].map(([en, ar, href]) => <Link key={href} href={href}><T en={en} ar={ar}/></Link>)}</div><div className="footer-note">© 2026 GrabMe S.A.L <span><T en="Lebanon · English / العربية" ar="لبنان · العربية / English"/></span></div></footer>; }
