/* eslint-disable @typescript-eslint/no-require-imports */
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),ts=require('typescript');
const compiled=ts.transpileModule(fs.readFileSync('src/lib/driver-intake.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;
function setup({enabled=true,uploadError=false,insertError=false}={}){const uploads=[],inserts=[];const context={exports:{},FormData,File,crypto,process:{env:{NEXT_PUBLIC_DRIVER_INTAKE_ENABLED:String(enabled),NEXT_PUBLIC_SUPABASE_URL:'https://example.invalid',NEXT_PUBLIC_SUPABASE_ANON_KEY:'fixture'}},require:()=>({createClient:()=>({storage:{from:bucket=>({upload:async(path,file)=>{uploads.push({bucket,path,file});return {error:uploadError}}})},from:table=>({insert:async payload=>{inserts.push({table,payload});return {error:insertError}}})})})};vm.runInNewContext(compiled,context);return {...context.exports,uploads,inserts};}
function form(){const data=new FormData();data.set('full_name','Test Driver');data.set('phone','000');data.append('previous_platforms','uber');data.append('previous_platforms','other');for(const name of ['driver_license_file','id_document_file','selfie_file'])data.set(name,new File(['fixture'],'private-name.png',{type:'image/png'}));return data;}
test('disabled intake performs no writes',async()=>{const s=setup({enabled:false});await assert.rejects(s.submitDriverApplication(form(),'en'),/disabled/);assert.equal(s.uploads.length,0)});
test('required documents are validated before any upload',async()=>{const s=setup(),data=form();data.delete('selfie_file');await assert.rejects(s.submitDriverApplication(data,'en'),/documents/);assert.equal(s.uploads.length,0)});
test('unsafe document format is rejected before any upload',async()=>{const s=setup(),data=form();data.set('selfie_file',new File(['x'],'test.svg',{type:'image/svg+xml'}));await assert.rejects(s.submitDriverApplication(data,'en'),/documents/);assert.equal(s.uploads.length,0)});
test('original table, bucket, payload and platform values survive',async()=>{const s=setup();await s.submitDriverApplication(form(),'ar');assert.equal(s.uploads.length,3);assert.ok(s.uploads.every(u=>u.bucket==='driver-documents'&&!u.path.includes('private-name')));assert.equal(s.inserts[0].table,'driver_applications');const p=s.inserts[0].payload[0];assert.equal(p.language,'ar');assert.equal(p.status,'new');assert.equal(p.previous_platforms,'uber,other');assert.equal(p.public_license_file,'');assert.ok(p.driver_license_file.startsWith('driver-licenses/'))});
test('upload failure never inserts application',async()=>{const s=setup({uploadError:true});await assert.rejects(s.submitDriverApplication(form(),'en'),/submission/);assert.equal(s.inserts.length,0)});
test('insert failure is not reported as success or retried',async()=>{const s=setup({insertError:true});await assert.rejects(s.submitDriverApplication(form(),'en'),/submission/);assert.equal(s.inserts.length,1)});
