/* eslint-disable @typescript-eslint/no-require-imports */
const {chromium}=require('C:/Users/User/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert=require('node:assert/strict'),fs=require('node:fs');
(async()=>{const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});const page=await browser.newPage({viewport:{width:1280,height:900}});const requests=[];let expired=false,submissionFailures=1;const applicationKeys=[];
await page.route('http://127.0.0.1:3291/**',async route=>{const req=route.request(),url=new URL(req.url());requests.push({path:url.pathname,method:req.method()});const headers={'access-control-allow-origin':'*','access-control-allow-headers':'content-type,authorization'};if(req.method()==='OPTIONS')return route.fulfill({status:204,headers});let data={};let status=200;
if(url.pathname==='/auth/send-otp'){assert.equal(req.postDataJSON().role,'PASSENGER');data={message:'OTP sent',resendAvailableInSeconds:30}}
else if(url.pathname==='/auth/verify-otp'){assert.equal(req.postDataJSON().otpCode,'123456');data={accessToken:'isolated-test-token',user:{role:'PASSENGER'}}}
else if(url.pathname.startsWith('/users/me/')){assert.equal(req.headers().authorization,'Bearer isolated-test-token');if(expired){status=401;data={message:'Expired'}}else if(url.pathname.endsWith('/profile'))data={name:'Isolated QA Passenger',currentSubscription:{status:'ACTIVE',endsAt:'2026-12-01T00:00:00Z',subscriptionPlan:{name:'Approved test plan'}},studentMember:{verified:true},corporateAccount:{companyName:'Isolated QA Company'}};else if(url.pathname.endsWith('/subscription-plans'))data=[{id:'test-plan',name:'Approved test plan',type:'PASSENGER',monthlyPrice:1,discountPercent:0,monthlyRideCredits:2}];else data={items:[{id:'test-wallet',amount:10,type:'CREDIT',createdAt:'2026-09-28T00:00:00Z'}],currency:'USD',nextCursor:null}}
else if(url.pathname==='/website/content')data=null;
else if(url.pathname==='/website/applications'){const body=req.postDataJSON();applicationKeys.push(body.idempotencyKey);assert.equal(body.consent,true);if(submissionFailures--){status=503;data={message:'Isolated response failure'}}else data={reference:'ISOLATED-TEST-REFERENCE',status:'RECEIVED'}}
else throw new Error('Unexpected route '+url.pathname);
await route.fulfill({status,headers,contentType:'application/json',body:JSON.stringify(data)})});
await page.goto('http://127.0.0.1:3190/account');await page.getByLabel('Phone number with country code').fill('+96170000000');await page.getByRole('button',{name:'Send verification code'}).click();await page.getByLabel('Six-digit verification code').fill('123456');await page.getByRole('button',{name:'Verify and sign in'}).click();await page.getByRole('heading',{name:'Isolated QA Passenger'}).waitFor();assert.equal(await page.evaluate(()=>Object.values(localStorage).includes('isolated-test-token')),false);await page.screenshot({path:'evidence/account-contract-fixture.png',fullPage:true});expired=true;await page.getByRole('button',{name:'Refresh',exact:true}).click();await page.getByRole('alert').waitFor();assert.equal(await page.getByRole('button',{name:'Send verification code'}).isVisible(),true);assert.equal(await page.getByText('Isolated QA Passenger',{exact:true}).count(),0);
await page.goto('http://127.0.0.1:3190/partners');for(const [name,value]of Object.entries({company:'Isolated QA Company',contact:'Test Person',email:'qa@example.test',locations:'Beirut'}))await page.locator(`input[name=${name}]`).fill(value);await page.locator('textarea').fill('Isolated browser API contract verification only.');await page.locator('input[type=checkbox]').check();await page.getByRole('button',{name:'Submit application',exact:true}).click();await page.getByRole('alert').waitFor();await page.getByRole('button',{name:'Submit application',exact:true}).click();await page.getByRole('status').waitFor();assert.equal(applicationKeys.length,2);assert.equal(applicationKeys[0],applicationKeys[1]);assert.equal(await page.getByRole('button',{name:'Submit application',exact:true}).isDisabled(),true);await page.screenshot({path:'evidence/application-contract-fixture.png',fullPage:true});assert.equal(requests.some(r=>r.path.includes('/activate')),false);fs.writeFileSync('evidence/account-contract-audit.json',JSON.stringify({mode:'INTERCEPTED ISOLATED FIXTURES, NOT LIVE BACKEND',checks:['same Passenger OTP payload','Bearer-scoped account GETs','membership status','eligible plans','wallet response envelope','memory-only token','401 clears account','intake retry preserves idempotency key','acknowledgment only after API reference','no subscription activation'],requests,limitations:['Does not demonstrate DB persistence, authorized Admin queue or app entitlement synchronization.']},null,2));await browser.close();console.log('Account and application browser contract checks passed using intercepted fixtures.');})().catch(e=>{console.error(e);process.exit(1)});
